apiVersion: v1
kind: Secret
metadata:
  name: solidfire-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "solidfire-csi.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Credentials for the SolidFire Cluster Admin
  username: "{{ .Values.solidfire.username }}"
  password: "{{ .Values.solidfire.password }}"
  endpoint: "{{ .Values.solidfire.endpoint }}"
  tenant: "{{ .Values.solidfire.defaultTenant }}"
