apiVersion: v1
kind: Secret
metadata:
  name: solidfire-secret
  namespace: default
type: Opaque
stringData:
  # Credentials for the SolidFire Cluster Admin
  username: "admin"
  password: "adminpassword"
