---
# Source: solidfire-csi/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: solidfire-secret
  namespace: solidfire-csi
  labels:
    helm.sh/chart: solidfire-csi-1.0.0
    app.kubernetes.io/name: solidfire-csi
    app.kubernetes.io/instance: solidfire-csi
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  # Credentials for the SolidFire Cluster Admin
  username: "admin"
  password: "admin"
  endpoint: "192.168.1.34"
  tenant: "admin"
