---
# Source: solidfire-csi/templates/storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: solidfire-bronze
  labels:
    helm.sh/chart: solidfire-csi-1.0.0
    app.kubernetes.io/name: solidfire-csi
    app.kubernetes.io/instance: solidfire-csi
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    meta.helm.sh/release-name: solidfire-csi
    meta.helm.sh/release-namespace: solidfire-csi
provisioner: csi.solidfire.com
parameters:
  csi.storage.k8s.io/fstype: "ext4"
  quota_max_total_capacity: "1099511627776"
  quota_max_volume_count: "90"
  storage_qos_policy_id: "1"
  csi.storage.k8s.io/provisioner-secret-name: solidfire-secret
  csi.storage.k8s.io/provisioner-secret-namespace: solidfire-csi
  csi.storage.k8s.io/controller-publish-secret-name: solidfire-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: solidfire-csi
  csi.storage.k8s.io/node-stage-secret-name: solidfire-secret
  csi.storage.k8s.io/node-stage-secret-namespace: solidfire-csi
  csi.storage.k8s.io/controller-expand-secret-name: solidfire-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: solidfire-csi
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
