apiVersion: v2
name: solidfire-csi
description: A community Helm chart for NetApp SolidFire CSI Driver
icon: https://raw.githubusercontent.com/scaleoutsean/solidfire-csi/refs/heads/master/helm/solidfire-csi/logo.svg
type: application
version: 1.0.0-beta.16
appVersion: "1.0.0-beta.16"